### ISSUE TITLE
Spike: cómo hacer validaciones de broken links y generación de indicadores eficientizando el proceso de chequeo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/monitoreo-apertura#240]
- Investigar dónde está el cuello de botella en `validate_catalog`

- Investigar uso de Threads dentro de pydatajson para manejar requests (validación de broken links) de manera concurrente

**Comment by lucaslavandeira** [comment]
Se puede refactorizar el código entero para ejecutar las validaciones de broken links en paralelo con las demás, utilizando la libreria estándar `multiprocessing` de Python. A continuación dejo un snippet de código ejemplo que realiza varios requests en paralelo, recolectando información resultante de cada request

```
