### ISSUE TITLE
Aplicar filtros booleanos en la escritura de los archivos de series

### ISSUE THREAD

**Issue by lrromero** [datosgobar/monitoreo-apertura#254]
Los csv de series de tiempo están incluyendo en sus columnas todos los tipos de indicadores. El comportamiento esperado es que si se marca en Falso el booleano de series para un tipo de indicador, este no aparezca en el archivo.

**Comment by abenassi** [comment]
Hacemos un branch aparte para corregir esto en una versión ahora
