### ISSUE TITLE
Loguear los errores de federacion

### ISSUE THREAD

**Issue by lalo73** [datosgobar/monitoreo-apertura#39]
Los errores de federacion deben loguearse en algun lado para monitoreo de parte de los desarrolladores.

**Comment by abenassi** [comment]
@lrromero implementamos este logging dentro de la estrategia del objeto de "Corrida de federación"

**Comment by abenassi** [comment]
@poligarcia @lrromero estuvimos revisando este tema con Melik, y llegamos a la conclusión de que queremos agregar *toda la información de los 3 tipos de errores* en el resultado de la "Corrida de federación", para que mirando sólo eso sea suficiente para disparar todas las acciones de corrección que hagan falta para mantener el número total de errores tendiendo a cero siempre.

La última vez habíamos hablado de que no queríamos perder el caracter de "resumen" del informe como está y que no queríamos poner un logging completo de errores por ese motivo. 

Después hablamos por Slack con @lrromero y llegamos a la conclusión de que era una buena idea que los errores de federación se vieran directamente en la Corrida de federación, debajo de los arrays "resumen".

Ahora nos parece que *debemos hacer lo mismo con los errores de "validación" también*. Los errores de "ausente" no tiene sentido porque toda la información necesaria ya está en el array (cuáles son los datasets ausentes).

Les parece abordarlo en este mismo issue??

**Comment by abenassi** [comment]
Ya que @lrromero va a abordar este tema, deberíamos evaluar si también se puede hacer el #67 en la misma secuencia, ya que es bastante sencillo y está en el mismo código que hay que modificar para abordar este issue.
