### ISSUE TITLE
Usar catalog_id en la base en lugar de los title de los catálogos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/monitoreo-apertura#53]
**Contexto**

Hoy en la tabla de indicadores de monitoreo-apertura el único campo que identifica el catálogo al que pertenecen los indicadores calculados es "title", que puede cambiar y no es un un "id".

Se desea incorporar el `catalog_id` a la tabla.

**Propuesta**

 + [ ] Modificar el método `generate_catalogs_indicators()` para que en el argumento `catalogs` también admita un `dict` en donde `catalog_id: catalog`. Esto permite (opcionalmente) pasar los ids de los catálogos al método y que devuelva el dato de "id" además del "title" en `indicators_list`. El fallback si se usa alguna de las alternativas anteriores, es hacer un `.get("identifier")` para devolver el `identifier` del catálogo si lo tiene, o dejar el valor nulo.

+ [ ] Modificar la corrida de generación de indicadores de `monitoreo-apertura` que usa este método para que utilice la opción nueva pasando un `dict` con los catálogos y sus ids, para empezar a guardar los indicadores asociados a los ids internos que usa monitoreo-apertura para cada catálogo.

**Notas**

+ Hacia atrás (el registro histórico), tratar de corregir la base agregando el catalog_id correspondiente a aquellos "title" cuya identificación no deje lugar a dudas. Los que presenten dudas, dejar con el catalog_id nulo.

+ Como `identifier` de un catálogo es un metadato no controlado por nosotros y no obligatorio, siempre se deben pensar estos re-factors donde se busca usar los ids de catálogos de forma tal que el id sea controlado por la aplicación y no por los data.json's originales, para controlar efectos inesperados

**Comment by abenassi** [comment]
Ids de nodos faltantes:

+ "aaip" es el title "Datos de la Agencia de Acceso a la Información Pública"
+ "cultura" es el title "....cultura..."
+ "salud" es el title "....MSAL..."

**Comment by poligarcia** [comment]
Esta tarea final la tackeamos en el issue #87
