### ISSUE TITLE
CD para ambiente de stg

### ISSUE THREAD

**Issue by lrromero** [datosgobar/monitoreo-apertura#64]
Implementar CD para ambiente de stg de monitoreo-apertura ante tags

**Comment by abenassi** [comment]
@lalo73 agregar un `HISTORY.md` con las versiones de los releases indicando qué cosas nuevas hay en cada release (como se hace en `pydatajson`)

**Comment by lalo73** [comment]
@abenassi este issue es solo para la implementacion.
El como manejar el release history debemos coordinarlo con el equipo.
Cierro este issue porque la implementacion ya está.
